### ISSUE TITLE
user specific information in rust/Cargo.toml

### ISSUE THREAD

**Issue by dustymabe** [cgwalters/git-evtag#14]
Contains the following:
```
[dependencies.git2]
path = "/home/walters/src/github/alexcrichton/git2-rs"

[dependencies.libgit2-sys]
path = "/home/walters/src/github/alexcrichton/git2-rs/libgit2-sys"
```

Which causes me to get an error because I don't have those directories. I'm new to rust so I don't know if this is normal or not.

**Comment by cgwalters** [comment]
Yeah, see https://github.com/cgwalters/git-evtag/pull/13#issuecomment-202188648

**Comment by cgwalters** [comment]
BTW see https://copr.fedorainfracloud.org/coprs/walters/git-evtag/ for precompiled binaries.

**Comment by dustymabe** [comment]
> BTW see https://copr.fedorainfracloud.org/coprs/walters/git-evtag/ for precompiled binaries.

sweet! - I searched for this in fedora but didn't look in copr :)

**Comment by dustymabe** [comment]
so just tried to use it to verify the latest tag from rpm-ostree and I'm seeing an issue:
```
$ $ rpm -q git-evtag
git-evtag-2016.1-1.fc22.x86_64
$ git checkout v2016.1
...
$ git-evtag verify v2016.1
gpg: Signature made Mon 28 Mar 2016 11:13:48 AM EDT using RSA key ID 21C13F0B
gpg: Good signature from "Colin Walters <walters@redhat.com>"
gpg:                 aka "Colin Walters <walters@verbum.org>"
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 1CEC 7A9D F7DA 85AB EF84  3DC0 A866 D7CC AE08 7291
     Subkey fingerprint: AB92 8A9C F8DD 0629 09C3  7BBD DC45 FD59 21C1 3F0B
error: Failed to resolve path '/home/dustymabe/Desktop/development/rpm-ostree/libglnx/.git': No such file or directory
```

Is this a misconfiguration or a bug?

**Comment by cgwalters** [comment]
You need to `git submodule update --init`.  It's a bug that we don't have a better error message in this situation.

**Comment by cgwalters** [comment]
Can you file this as a new issue?

**Comment by dustymabe** [comment]
> Can you file this as a new issue?

here ya go: https://github.com/cgwalters/git-evtag/issues/16
