### ISSUE TITLE
gmane links are dead

### ISSUE THREAD

**Issue by purpleidea** [cgwalters/git-evtag#26]
FYI

**Comment by zbeekman** [comment]
Came here for the same reason... the links to the git mailing list discussions are broken. Would be great to update.

**Comment by cgwalters** [comment]
Fixed by https://github.com/cgwalters/git-evtag/commit/7393a318e667580a7f00ea386dc21c1933eac85a

Here's a [direct link to marc.info](https://marc.info/?l=git&m=142513489318999&w=3).
