### ISSUE TITLE
2022.1 release

### ISSUE THREAD

**Issue by smcv** [cgwalters/git-evtag#44]
I'd like to do a 2022.1 release, mainly to incorporate @pwithnall's submodule fixes and my Meson build system. @cgwalters, do you want to tag that release, or would you prefer me to do it, or are there important changes pending that mean we should delay it?

Draft release notes: https://github.com/cgwalters/git-evtag/releases/tag/untagged-3a452443d2570a6ad3d6

Do I understand correctly that this project does not officially release Autotools `make dist` tarballs or a canonical `git archive` tarball, only git tags signed using the project itself?

Unless @cgwalters feels differently, I would be inclined to do this release with both Autotools and Meson included, and then remove Autotools afterwards. Does that seem right?

**Comment by pwithnall** [comment]
> Unless @cgwalters feels differently, I would be inclined to do this release with both Autotools and Meson included, and then remove Autotools afterwards. Does that seem right?

That seems prudent

**Comment by cgwalters** [comment]
Yeah, supporting the need for explicit archives was part of the rationale of this project, but I have no objections to doing so either...

Release notes look good to me. 

No strong opinion on autotools removal before or after a release; if I had to vote I'd say just pull off the bandaid and do it before the release.

**Comment by smcv** [comment]
> No strong opinion on autotools removal before or after a release; if I had to vote I'd say just pull off the bandaid and do it before the release.

I think having an overlap is useful, and you said this isn't a strong opinion, so I'm going to do one last release with both Autotools and Meson and then remove Autotools.

**Comment by smcv** [comment]
Released v2022.1.
